target(
    name = "google_api",
    dependencies = [
        "test/lib/google:google_api_tests",
    ],
)

target(
    name = "pagerduty_api",
    dependencies = [
        "test/lib/pagerduty:pagerduty_tests",
    ],
)
