python_tests(
    name = "pagerduty_tests",
    sources = ["pagerduty_tests.py"],
    dependencies = [
        "3rdparty/python:mock",
        "3rdparty/python:pycrypto",
        "libs:pagerduty",
    ],
)
